const mongoose = require('mongoose');

const applicationSchema = new mongoose.Schema({
    // Relationships — THE JOIN BETWEEN CANDIDATE AND JOB
    candidateId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, "Candidate ID is required"],
    },
    jobId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Job',
        required: [true, "Job ID is required"],
    },
    resumeId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Resume',
        required: [true, "Resume ID is required"],
    },

    // MATCH SCORE — THE CORE FEATURE OF THE PLATFORM
    matchScore: {
        type: Number,          // e.g., 87.5 (percentage)
        min: [0, "Score cannot be below 0"],
        max: [100, "Score cannot exceed 100"],
        default: null,         // null until AI processing completes
    },

    // Detailed scoring breakdown 
    scoreBreakdown: {
        type: {
            skillsMatch: { type: Number, default: 0 },
            experienceMatch: { type: Number, default: 0 },
            educationMatch: { type: Number, default: 0 },
            overallFit: { type: Number, default: 0 },
        },
        default: {},
    },

    // Skills gap analysis
    matchedSkills: {
        type: [String],        // Skills the candidate has
        default: [],
    },
    missingSkills: {
        type: [String],        // Skills the job needs but candidate lacks
        default: [],
    },

    // AI-generated feedback
    aiFeedback: {
        type: String,          // "Strong match in backend skills, but lacks cloud experience..."
        default: "",
    },
    resumeImprovementTips: {
        type: [String],
        // ["Add AWS certification", "Highlight leadership experience more clearly"]
        default: [],
    },

    // Suggested interview questions generated by AI
    suggestedInterviewQuestions: {
        type: [{
            type: {
                type: String,
                enum: ['technical', 'behavioral', 'situational', 'cultural_fit'],
            },
            question: String,
            suggestedAnswer: { type: String, default: "" },
        }],
        default: [],
    },

    // Application lifecycle
    status: {
        type: String,
        enum: ['applied', 'under_review', 'shortlisted', 'rejected', 'hired'],
        default: 'applied',
    },

    // Recruiter actions
    recruiterNotes: {
        type: String,
        default: "",
        trim: true,
    },
    isShortlisted: {
        type: Boolean,
        default: false,
    },
    shortlistedAt: {
        type: Date,
        default: null,
    },
    reviewedAt: {
        type: Date,
        default: null,
    },

    // AI processing status
    aiProcessingStatus: {
        type: String,
        enum: ['pending', 'processing', 'completed', 'failed'],
        default: 'pending',
    },
}, {
    timestamps: true,
});

// A candidate can only apply once per job
applicationSchema.index({ candidateId: 1, jobId: 1 }, { unique: true });

const Application = mongoose.model("Application", applicationSchema);

module.exports = Application;